### ISSUE TITLE
Traffic detail per ip

### ISSUE THREAD

**Issue by darrepac** [oofnikj/docker-openwrt#21]
Hi

Nice dashboard.
There is no way to display the traffic per local ip? instead (or in addition to) of showing per interface...to display and track down which local device is using most of the traffic

**Comment by oofnikj** [comment]
Hi @darrepac, there isn't a built-in way to get that information into Grafana with OpenWrt. For that I wrote [iptmon](https://github.com/oofnikj/iptmon).

Just realized there is no link to that project from the monitoring readme - I suppose that would be helpful!

**Comment by darrepac** [comment]
Yes and as I am very smart, I found it myself (and post a question about it into openwrt forum), but because as I am not so smart, I am so sure that I have all the prerequisite neither sure about how to install everything :)
But discussion to be followed elsewhere :)

**Comment by oofnikj** [comment]
Right, closing this issue then.
