### ISSUE TITLE
Other containers cannot access LAN

### ISSUE THREAD

**Issue by Flamingi** [oofnikj/docker-openwrt#27]
I have installed OpenWrt in Docker on Ubuntu, it's working fine and as expected. I have used the default configuration with one macvlan interface for WAN and a bridge for LAN. My Ubuntu host can be reached with `192.168.1.1`, while OpenWrt has the IP `192.168.1.2`. Now I want to run other containers using the standard bridge interface (i.e. `docker0`) and I have observed the following behavior:

- I can access the docker container from my LAN (e.g. I have installed Home Assistant and can access it from my desktop PC via `192.168.1.1:8123`)
- Containers can communicate between each others (e.g. Home Assistant can access my MQTT broker running on the same host via `192.168.1.1:8883`)
- Containers can access the internet (e.g. `ping 8.8.8.8` or `ping google.com` work)
- Containers cannot access my LAN (e.g. `ping 192.168.1.233` does not work)
- If I connect the container to the bridge network created by OpenWrt I can access my LAN, but on next boot OpenWrt cannot start as the other container takes the network first and then it is already in use.

Is this expected behavior? How do I fix it?

**Comment by hllhll** [comment]
> * If I connect the container to the bridge network created by OpenWrt I can access my LAN, but on next boot OpenWrt cannot start as the other container takes the network first and then it is already in use.
I Had the same issue, I ended up running my docker-compose YAML file after ["ready"](https://github.com/oofnikj/docker-openwrt/blob/master/run.sh#L218) on not on start.

**Comment by Flamingi** [comment]
> I Had the same issue, I ended up running my docker-compose YAML file after ["ready"](https://github.com/oofnikj/docker-openwrt/blob/master/run.sh#L218) instead of on boot.

This fixed it, thank you very much.
