### ISSUE TITLE
It would be great if there is a version without wifi

### ISSUE THREAD

**Issue by SmallPackage** [oofnikj/docker-openwrt#8]
I get a device without wifi,  so I just comment all wifi stuffs

when I do " make run", I got 
"""
Could not find config file.
Usage: run.sh [/path/to/openwrt.conf]
"""

**Comment by oofnikj** [comment]
Hi @SmallPackage, can you please try to checkout the branch `nowifi` and try it?

Also, you need to create a config file by copying the example config, e.g.
```
$ cp openwrt.conf.example openwrt.conf
```

**Comment by oofnikj** [comment]
Implemented in #9

**Comment by SmallPackage** [comment]
that's great! 
nowifi branch start up succeefully
But, I just got confused about interface config, and couldn't got the dhpcd of my main router (which from my ips) work correctly with docker macvlan interface. so I failed to access the web administrator page;

And I have tried some other images such as "crazygit/openwrt-x86-64", or "openwrt/rootfs", and got even more confusing;

I realized, I should learn more about this topic, So that I could tell what I'm exactly doing;
